version: '3.8'

services:
  gemini-nano-banana-discord-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./.cache:/app/.cache
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DASHBOARD_HOST=0.0.0.0
      - DASHBOARD_PORT=8000